# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Salvador Gironès'
url:              http://salvadorgirones.com
baseurl:          /

author:
  name:           'Salvador Gironès'
  url:            https://salvadorgirones.com

# Custom vars
version:          1.0.0
